- import_tasks: 02a-install.yml
  when: sr_installed.msg != "src and dest are required for creating links"

- import_tasks: 02b-install.yml
  when: sr_installed.msg == "src and dest are required for creating links"

- name: Creating systemd-unit to schema-registry
  template:
    src: systemd/schema-registry.j2
    dest: /usr/lib/systemd/system/schema-registry.service
    owner: root
    group: root
    mode: 0644
    backup: yes
    force: yes
  register: sr_unit
  notify: Restart schema-registry

- name: Creating symbolic link to systemd-unit
  file:
    src: /usr/lib/systemd/system/schema-registry.service
    dest: /etc/systemd/system/multi-user.target.wants/schema-registry.service
    owner: root
    group: root
    state: link
  notify: Restart schema-registry
  when: sr_unit|changed
