kafka_cluster_config:
 name: "ps-ouroboros-prd"
 zkHosts: "{{ groups['zookeeper'] | join(':2181,') }}:2181"
 kafkaVersion: 0.11.0.0
 jmxEnabled: "true"
 jmxUser: ""
 jmxPass: ""
 jmxSsl: "false"
 logkafkaEnabled: "false"
 pollConsumers: "true"
 filterConsumers: "true"
 activeOffsetCacheEnabled: "true"
 displaySizeEnabled: "false"
 tuning.brokerViewUpdatePeriodSeconds: 30
 tuning.clusterManagerThreadPoolSize: 10
 tuning.clusterManagerThreadPoolQueueSize: 100
 tuning.kafkaCommandThreadPoolSize: 10
 tuning.kafkaCommandThreadPoolQueueSize: 100
 tuning.logkafkaCommandThreadPoolSize: 10
 tuning.logkafkaCommandThreadPoolQueueSize: 100
 tuning.logkafkaUpdatePeriodSeconds: 30
 tuning.partitionOffsetCacheTimeoutSecs: 5
 tuning.brokerViewThreadPoolSize: 10
 tuning.brokerViewThreadPoolQueueSize: 1000
 tuning.offsetCacheThreadPoolSize: 10
 tuning.offsetCacheThreadPoolQueueSize: 1000
 tuning.kafkaAdminClientThreadPoolSize: 10
 tuning.kafkaAdminClientThreadPoolQueueSize: 1000
 securityProtocol: "PLAINTEXT"
