- name: Creating kafka-rest group
  group:
    name: kafka-rest
    gid: 1540
    state: present
    system: yes

- name: Creating kafka-rest user
  user:
    name: kafka-rest
    comment: "kafka-rest User"
    uid: 1640
    shell: /usr/sbin/nologin
    group: kafka-rest
    createhome: no
    state: present
    system: yes
    force: yes
